### ISSUE TITLE
how to run htm-cla-visualizer

### ISSUE THREAD

**Issue by ynjiun** [solovyevk/htm-cla-visualizer#10]
I have installed successfully. But when I say ./run.bat in my install directory, I got the following error message:
Error: Could not find or load main class htm.visualizer.Viewer

could you please help? thanks.

-Paul

**Comment by ynjiun** [comment]
then I copy out htm-visualizer-1.1.jar from ./target and rename it to "htm-visualizer.jar"
when I "source run.sh" I got following error message:
ypw@ypw-VirtualBox-c1:~/development/htm-cla-visualizer$ source run.sh
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/commons/logging/LogFactory
    at htm.visualizer.Viewer.<clinit>(Viewer.java:27)
Caused by: java.lang.ClassNotFoundException: org.apache.commons.logging.LogFactory
    at java.net.URLClassLoader$1.run(URLClassLoader.java:366)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
    ... 1 more

**Comment by ynjiun** [comment]
[problem solved]
1. create a ./lib
2. download commons-logging-1.2 from https://commons.apache.org/proper/commons-logging/download_logging.cgi to ./lib
3. modify run.sh -classpath to following:
#!/bin/sh
java -classpath "lib/commons-logging-1.2/commons-logging-1.2.jar:lib/log4j-1.2.9.jar:target/htm-visualizer-1.1.jar" htm.visualizer.Viewer
1. source run.sh
   done!

**Comment by ynjiun** [comment]
to run, say:
source run.sh

**Comment by solovyevk** [comment]
Sorry just got to this. I didn't test it much in Unix :)

**Comment by ynjiun** [comment]
Kirill,

No problem. It’s an impressive work. I am playing with it.

-Paul
